### ISSUE TITLE
falsches platzieren von country info

### ISSUE THREAD

**Issue by HolgerJeromin** [mueschel/OsmLaneVisualizer#2]
Geniales Tool hast du da :-)
Ich habe ein etwas kompliziertes Schild.
http://www.mapillary.com/map/im/MTMtr038L3_tFeOHQSSGyA
https://www.openstreetmap.org/way/222577615

In deiner Anzeige ist das NL jedoch leider nicht neben Vaals. Mein Bildschirm ist größer als fullHD, daran sollte es also nicht liegen :-)

http://osm.mueschelsoft.de/cgi-bin/render.pl?url=%3Cosm-script+output%3D%22json%22+timeout%3D%2225%22%3E%3Cunion%3E%3Cquery+type%3D%22way%22%3E%3Cid-query+ref%3D%22222577615%22+type%3D%22way%22%2F%3E%3C%2Fquery%3E%3C%2Funion%3E%3Cprint+mode%3D%22body%22+order%3D%22quadtile%22%2F%3E%3Crecurse+type%3D%22down%22%2F%3E%3Cprint++order%3D%22quadtile%22%2F%3E%3C%2Fosm-script%3E&start=1

**Comment by mueschel** [comment]
Im Augenblick werden Länderkennzeichen wie auch die destination:ref gesammelt am unteren Rand angezeigt. Es ist etwas kompliziert, das richtig hinzubekommen - bei manchen Schilder (siehe auch das Beispiel im Wiki) stehen die Symbole auch einzeln, unabhängig von den Destinations.
Ich überlege, ob ich die Länder dann neben den Zielen anordne, wenn destination:country genausoviele Semikola enthält wie destination selbst. Wenn das nicht der Fall ist, dann weiterhin unten.

**Comment by HolgerJeromin** [comment]
Oh, stimmt. Das mit country scheint komplizierter als gedacht.
Dein Plan hört sich sinnvoll an. :-)

**Comment by mueschel** [comment]
Ist jetzt eingebaut.

**Comment by HolgerJeromin** [comment]
cool, danke
