### ISSUE TITLE
Support destination symbols separated with a comma

### ISSUE THREAD

**Issue by daganzdaanda** [mueschel/OsmLaneVisualizer#20]
On the wiki page for [Key:destination:symbol](https://wiki.openstreetmap.org/wiki/Key:destination:symbol) it says 

> Symbols in a row are separated with , comma. Symbols and rows of symbols below each other are separated with ; semicolon. Blanks are not used.

I tried this out on https://www.openstreetmap.org/way/325443718 as the signage there has a few symbols in one row (centre, "Messe" and stadium; I chose to switch centre and Messe for simplicity)
![a73-nbg-sued-5s](https://user-images.githubusercontent.com/7693297/228969921-96476505-7bb9-455b-a4a8-8cb0b9f6607c.JPG)

It looks as if symbols separated by commas are not yet supported. Or maybe I got confused while tagging and have mixed up something? 

Thanks for this great visual tool! It really helps getting the lanes tagged right!

**Comment by mueschel** [comment]
You're right, the Lanes tool doesn't support this tagging, and I don't plan to add it in the near future. In fact my plan is to separate the lane view from destination signs to be more flexible.

You can check out this way in my destination sign tool:
http://osm.janmichel.eu/destinationsign/example/#way=325443718&namedroutes=1&fromarrow=0&include_sgn=1&include_way=1&country=

There's also a sandbox to check destination tagging before uploading:
http://osm.janmichel.eu/destinations/example/sandbox.htm
