### ISSUE TITLE
Add support for non-Latin scripts

### ISSUE THREAD

**Issue by Dimitar5555** [mueschel/OsmLaneVisualizer#22]
Currently if you enter `Автомагистрала Тракия` in the `A relation with name` box and press go, you get only question marks. The same thing happens if you replace those question marks in the query box with the proper text and press go.

**Comment by mueschel** [comment]
Hi,
thanks for pointing this out... It's the never-ending story of UTF-8. It worked at some point in the past. 

Now it should be ok again.

**Comment by Dimitar5555** [comment]
Thanks! It's working now.
