### ISSUE TITLE
falsche lanes Anzeige bei Verwendung von backward/forward

### ISSUE THREAD

**Issue by it4workflow** [mueschel/OsmLaneVisualizer#5]
Servus,
habe hier folgendes Phänomen bei der Verwendung von lanes bei spezieller Attributierung mit backward/forward:

![image](https://cloud.githubusercontent.com/assets/8296940/6535841/4eb320a4-c448-11e4-83c4-a88053be32dc.png)
https://www.openstreetmap.org/way/294041816 (korrekte Anzeige)
https://www.openstreetmap.org/way/294041808 (fehlerhafte Anzeige)
Bei beiden Ways ist lanes=3 eingetragen, nur wird bei einem turn:lanes:forward alles korrekt angezeigt, bei Verwendung von turn:lanes:backward aber dann eine Fahrspur mehr als lanes=3 überhaupt vorgibt. 
Oder hängt es am lanes:*?
Es scheint zumindest immer dann aufzutreten, wenn man das jeweils andere, was man ja errechnen kann/könnte, nicht mit angibt. In den Fällen, in denen alles explizit angegeben wird, klappts:

![image](https://cloud.githubusercontent.com/assets/8296940/6535893/e87699e6-c448-11e4-9a75-8900f7fced8b.png)

Viele Grüße
Harald Hartmann

**Comment by mueschel** [comment]
Die Behandlung von diesem Fall (nur :backwards vorhanden, keine :forward) sollte jetzt besser sein. Diesen Teil werde ich aber nochmal umschreiben müssen, bis alles passt. Z.B. gibt es tolle Spezialfälle, die noch nicht richtig ausgewertet werden. Folgender Weg hätte tatsächlich zwei Spuren in forward-Richtung...

`lanes = 3
access:lanes:backward = yes|no
bicycle:lanes:backward = yes|designated`
